PAY_NOW_BTN = "//span[text()='Pay now ']"
SPLIT_BILL_BTN = "//span[text()='Split bill']"
CUSTOM_AMNT_BTN = "select-custom"
CUSTOM_AMNT_FIELD = "fullWidth"
CONFIRM_BTN = "split-bill"
FIVE_TIP_BTN = "tip_5"
CARD_NUMBER_IFRAME = "cardNumber"
CARD_NUMBER_INPUT = "checkout-frames-card-number"
EXPIRY_DATE_IFRAME = "checkout-frames-expiryDate"
EXPIRY_DATE_INPUT = "checkout-frames-expiry-date"
CVV_IFRAME = "cvv"
CVV_INPUT = "checkout-frames-cvv"
CHECK_OUT_BTN = "checkout-action-btn"
PAYMENT_IFRAME = "cko-3ds2-iframe"
PASSWORD_INPUT = "password"
CONTINUE_BUTTON = "txtButton"
APP_URL = "https://app-staging.qlub.cloud/qr/ae/dummy-checkout/90/_/_/1827c10c80"
SPLIT_AMNT = "10"
CARD_INFO = "4242424242424242"
EXPIRY_DATE = "0226"
CVV_INFO = "100"
PASSWORD_INFO = "Checkout1!"
LOADING_SCREEN = "Splash_container__iwFip"
SUCCESSFUL_PAYMENT = "//p[@class='MuiTypography-root MuiTypography-body1 css-1dbb4wf']"